name: test

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  run-vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run vitest
        run: npm test run >> $GITHUB_STEP_SUMMARY
